# Travis-CI Build for OpenRA
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.
language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get install mono-gmcs cli-common-dev libgl1-mesa-glx libopenal1 libfreetype6 dpkg rpm nsis markdown
cache: apt

# Run the build script
# call RALint to check for YAML errors
script:
 - make dependencies
 - make all
 - make test

# Only watch the development branch and tagged release.
branches:
 only:
   - /^release-.*$/
   - /^playtest-.*$/
   - /^pkgtest-.*$/
   - bleed

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true

before_deploy:
 - DOTVERSION=`echo $TRAVIS_TAG | sed "s/-/\\./g"`
 - cd packaging
 - mkdir build
 - ./package-all.sh $TRAVIS_TAG build
deploy:
  provider: releases
  api_key:
    secure: "cMC68erxuf0jb4Pe0sOH4m1f7I2LWPUatD9BC0WeZ9PwTnWOzrm0hnjZIES4TTKVo8WIfZIiCfxpdAFeoh6bomG2MsKwSKMc8qHGhfNGqPnyzYh6zdPZaA+4Q3TDQI3DrziyDnQUFeH1h/7UZLDLxtDrOtcYcGdNg5VjvV9fJ7g="
  file:
    - build/OpenRA-$TRAVIS_TAG.exe
    - build/OpenRA-$TRAVIS_TAG.zip
    - build/openra-$DOTVERSION-1-noarch.rpm
    - build/openra_$DOTVERSION_all.deb
  skip_cleanup: true
  on:
    all_branches: false
    tags: true
    repo: OpenRA/OpenRA
