# Travis-CI Build for OpenRA
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.
language: c

# Make sure build dependencies are installed.
before_install:
 - sudo apt-get update
install:
 - sudo apt-get install mono-gmcs cli-common-dev libsdl1.2debian libgl1-mesa-glx libopenal1 libfreetype6

# Run the build script and call RALint to check for YAML errors
script:
 - make all
after_script:
 - make test

# Only watch the development branch.
branches:
 only:
   - bleed

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
